### ISSUE TITLE
84 byte header

### ISSUE THREAD

**Issue by nicoco007** [Pupix/lol-wad-parser#10]
Have you tried getting something out of the v2 header? This is what I've gotten so far:

![2017_03_02_00_32_49_010_editor_c_users_nicolas_desktop_chogath wad client_](https://cloud.githubusercontent.com/assets/1349975/23494655/195a02ca-fee2-11e6-9b83-1fcda44f5706.png)

But I have no clue what the red and orange parts might represent. Do you have an idea?

**Comment by Pupix** [comment]
Yes, it contains the file signature ([ECDSA](https://en.bitcoin.it/wiki/Elliptic_Curve_Digital_Signature_Algorithm)). It's used by the game to validate the WAD file.

```
byte ECDSALength;
byte ECDSA[ECDSALength];
byte ECDSAPadding[83 - ECDSALength];
```

**Comment by nicoco007** [comment]
Oh, thanks! ~So I'm guessing that because of this, it is no longer possible to edit these files?~ Nevermind, just read another issue explaining exactly that.
