### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed

### ISSUE THREAD

**Issue by yanchao7511461** [Pupix/lol-wad-parser#2]
Hi, when I use the scrpt to extract a wad file, the V8 engine shows me "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed". I found the wad file to extract was too large . its size is 520 MB. So I think the script may some errors when target file too large.

**Comment by Pupix** [comment]
Hello!

Could you tell me which file you are trying to extract? As of now it loads all the data into memory before extracting it, which could be causing the problem you are having.

Is this your problem? A log of the error would be nice.

**Comment by Pupix** [comment]
Fixed in @3f010f535554746c92e638e6f2c7c1f74f18f31f
