### ISSUE TITLE
Improvement: Separate the hashes by project and wad file

### ISSUE THREAD

**Issue by honux** [Pupix/lol-wad-parser#21]
Following up the idea provided on https://github.com/Pupix/lol-wad-parser/issues/9, I would like to suggest to separate the hashes by project and wad file.

[hashes.zip](https://github.com/Pupix/lol-wad-parser/files/1491858/hashes.zip)
This is a list of known hashes separated and some more I've managed to find myself.

**Comment by Pupix** [comment]
Thanks for this. I will look into it and see how can be implemented into the parser this weekend.

**Comment by Pupix** [comment]
Finally got around doing this. Now the hashes have been split up in `region/local`.
