### ISSUE TITLE
Add new Hashes 

### ISSUE THREAD

**Issue by TomTomB** [Pupix/lol-wad-parser#22]
Hi, 
I was wondering if there is any way to get the hashes for newer assets that e.G came with update 8.1.

Anyways - the project is super cool so far and saves me a lot of time.
Getting the right names/folders for the extracted data would just be the "icing on the cake".

Cheers

**Comment by Pupix** [comment]
Getting new hashes is not really straight forward. You need to know the paths beforehand, sniffing the .exe or some other method, then run the hashes against an xxhash algorithm.
Once you have everything mapped you can make a PR with [updated hashes](https://github.com/Pupix/lol-wad-parser/tree/master/hashes/league_client).

I will add more hashes when I have time, atm I am working on other tools for another game (Path of Exile).
