### ISSUE TITLE
I am completely new to this

### ISSUE THREAD

**Issue by michin1** [Pupix/lol-wad-parser#24]
I began looking into this to change lol summoner name filter and club tag character filter and limit. I was wondering if you could tell me how to do this please. I am completely new to all of this and do not know what I'm even looking at. Help would be greatly appreciated.

**Comment by Pupix** [comment]
Can't help you bypass rulesets/logic set by Riot

**Comment by michin1** [comment]
this just made me laugh im sorry. considering most of the things people will use these for will directly violate what riot specifically asks you NOT to do. thanks. i guess.

**Comment by michin1** [comment]
just needed to know how to run the damn thing.
