### ISSUE TITLE
error~

### ISSUE THREAD

**Issue by yanchao7511461** [Pupix/lol-wad-parser#3]
![image](https://cloud.githubusercontent.com/assets/7982646/16256043/98af05e8-3881-11e6-9f22-561132eaf4e2.png)

**Comment by Pupix** [comment]
what node version are you using?

**Comment by yanchao7511461** [comment]
v4.4.5.
hi , can I get your email?  I have some questions  and hope your help .

**Comment by Pupix** [comment]
That node version doesn't support ES2015 destructuration. Just update node and the problem will go away.

My email is [here](https://github.com/Pupix/lol-wad-parser/blob/master/package.json#L9).
