### ISSUE TITLE
Hashes

### ISSUE THREAD

**Issue by PaulBGD** [Pupix/lol-wad-parser#4]
Hi Pupix, this isn't as much of an issue as it is a question, but as I can't find any other way to contact you I'll put this here. How did you generate the hashes.json file? I'm trying to figure out what kind of hash it is, to no success.

**Comment by Pupix** [comment]
Hello!

The hash algorithm is called XXH64, and the strings were gathered from referencing links inside the files.

About the contact issue, [check this out](https://github.com/Pupix/lol-wad-parser/blob/master/package.json#L9).

Cheers!

**Comment by PaulBGD** [comment]
Also, are the hashes truncated at all? I noticed that the sha256s were just the first 8 bytes.

**Comment by Pupix** [comment]
Yes, they are truncated in the file structure.
