### ISSUE TITLE
Files not being extracted to the proper directory

### ISSUE THREAD

**Issue by AKPWebDesign** [Pupix/lol-wad-parser#9]
I've noticed when I extract .wad data, there are usually quite a few files that are simply extracted to the root directory of where I choose to extract, with a hash as the filename, but at the same time, there are lots of files that are properly extracted to the right folder. Example: ![example image](http://i.imgur.com/nL1IBjt.png)

**Comment by Pupix** [comment]
Hello!

This happens because they are not mapped yet. [Here](https://github.com/Pupix/lol-wad-parser/blob/master/lib/hashes.json)'s the list of known hashes.

Not much can be done about this because the hashes are the only thing `.wad` files provide. When a plugin requires a file, the C++ services run the path through a `xxhash64` and return the resource with the corresponding hash.

All the mapping on my part is either done by hand or parsing the HTML plugin files from the league client.

PR with more hashes are always welcome.

**Comment by AKPWebDesign** [comment]
Ah. In that case, I'll start working on a PR for everything I can. :+1:

**Comment by Pupix** [comment]
Closed due to inactivity

**Comment by honux** [comment]
Is the hashed with a constant seed?
If it isn't, is there any way to adquire it? - That would make incredibly easy to extract most of the files with the correct name.

**Comment by Pupix** [comment]
Yes. The seed is always `0`. Here's how to create the hashes:

```js
const XXH = require('xxhashjs');
const PATH= 'plugins/rcp-be-lol-game-data/global/default/v1/champion-splashes/11/11002.jpg';

let hash = XXH.h64(PATH, 0).toString(16);

//Split the hash
let low = hash.slice(0, 8);
let high = hash.slice(8);

// Remove unnecessary padding
high = high.replace(/^0*/, '');

// Put the hash back together
hash = low + high;

console.log(`"${hash}": "${path}",`);
```

This will be logged:
`"4684f5ef38fd9c7": "plugins/rcp-be-lol-game-data/global/default/v1/champion-splashes/11/11002.jpg"`

**Comment by honux** [comment]
This has proven to be harder than I expected, lol.
But most likely, I will be able to help by making a generic hackish that will decode most of the data.

There is an issue on your hashing code: It removes the padding zero of the "high" part - which should not be removed.
A given example is the following file:
`"plugins/rcp-be-lol-game-data/global/default/v1/champion-sfx-audios/14.ogg"`
Using your code, it gives the following hash: `cd5375d453140b`, which is not a valid file.
Without removing the padding zeros from the high parte, gives the following hash `cd5375d4053140b`, which is a valid file.

Therefore, a simple `let hash = XXH.h64(PATH, 0).toString(16);` is enough :P

edit:
After some further investigation, it seems that sometimes it removes the padding, and sometimes it does not. Still investigating though.

edit2:
Found out the issue.
Whenever there is a padding zero on the low part, the slice becomes erroneous, therefore generating a wrong hash.
This is the corrected hashing code:

```javascript
    const XXH = require('xxhashjs');
    const PATH = 'plugins/rcp-be-lol-game-data/global/default/v1/champions/28.json';
    let hash_str = XXH.h64(PATH, 0).toString(16);

    // Make sure it has 16 length
    while (hash_str.length < 16) hash_str = "0" + hash_str;
    
    //Split the hash
    let low = hash_str.slice(0, 8);
    let high = hash_str.slice(8);

    // Remove unnecessary padding
    low = low.replace(/^0*/, '');
    high = high.replace(/^0*/, '');

    // Put the hash back together
    hash_str = low + high;
    console.log(`"${hash_str}": "${PATH}",`);
```

Side Note: The path **must** be on lowercase, even though it might be passed as mixed case, Example:
```
"lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Ascension/img/icon-defeat.png" -> "plugins/rcp-be-lol-game-data/global/default/content/src/leagueclient/gamemodeassets/ascension/img/icon-defeat.png" -> "3ff9a9185aa3eaa0"
```

----

Is there any chance to make the hash optional? So we would not need to keep updating the hash file and we would be able to work on a separated project that solves this issue.

**Comment by Pupix** [comment]
Good catch on that padding.

**About the optional hashing:**
Without the paths you would just have a huge list of random files with no actual meaning. I don't see how that would be helpful as you'd need to open each file to see what's inside.

Do you have any use cases for pathless scenario over the current situation, that tries its best to cut out the work for you?

**About the separation of projects:**
Having two separate projects wouldn't remove the cat and mouse update problem, having to constantly update the hash list. 

Whenever there would be a hash update there would need to be a new npm/github version. If we use a `lol-wad-parser-hashes` as a dependency for `lol-wad-parser` we either have to bump the versions of both projects at once or use a version range `(^1.0.0)` and risk having people with the same `lol-wad-parser` version behave differently because of the `lol-wad-parser-hashes` dependency might be different.

Having a version range also creates that problem of not being able to know when there's been an update on the hashes module.

**Comment by honux** [comment]
I've attached a work in progress of a 'hash decoder'. At least right now, it just work with the 'rcp-be-lol-game-data', but that might give you and idea of what I'm thinking.

I believe that some files are pretty much constant (At least using the last 3 patches, they seems to match): 'champion-summary.json', 'profile-icons.json', 'items.json', etc. Parsing those files, it is possible to decode almost all the hashes. And this idea might be used on other plugins as well.

[rename-files.txt](https://github.com/Pupix/lol-wad-parser/files/966836/rename-files.txt)

PS: Please don't judge my lack of skills while programming node.js / javascript, I'm pretty much trying to get the job done here.
PS2: With that script I'm able to decode almost all the files on 'rcp-be-lol-game-data'

**Comment by Pupix** [comment]
Feel free to create a PR with the new hashes when you finish this.

**Note:**
The LCU files are not the only `.wad`s in the game. `RAF` archives also contain `.wad.client` files inside `DATA/FINAL/*`.

**Comment by honux** [comment]
**About the optional hashing:**

Although it would be a lot of random files, it wouldn't be linked to a single project.
Right now, the known hashed files belong to the 'default' language, even though some files also exists with the exact same name under their language (Eg: '/plugins/rcp-be-lol-game-data/global/default/v1/champion-summary.json' also exists on pt_br [/plugins/rcp-be-lol-game-data/global/pt_br/v1/champion-summary.json] and on all other languages). Hashing all the files, on all possible languages (If I remember correctly, there are 28 different languages available on league) would make an unnecessary large file.

I propose here a generic hashing method, in which providing the correct file path it would always generate a valid hash: 
```javascript
function hash_name(plugin_name, location, file_path) {
    if (!file_path) {
        return "";
    }

    var real_path = file_path.replace('/lol-game-data/assets', `plugins/${plugin_name}/global/${location}`).toLowerCase();
    var hashed_str = xxhash.h64(real_path, 0).toString(16);

    return hashed_str;

    // For some reason, some files require to strip the lower part of the string, still need to investigate why and when that happens
    // var high = hashed_str.slice(0, hashed_str.length-8).replace(/^0*/, '');
    // var low = hashed_str.slice(-8).replace(/^0*/, '');
    // return high+low;
}
```
So it is possible to always access a given file if the correct path is provided. Eg:
```javascript
hash_name('rcp-be-lol-game-data', 'default', '/lol-game-data/assets/v1/champion-summary.json'); // 9364e80b15967d0
hash_name('rcp-be-lol-game-data', 'pt_br', '/lol-game-data/assets/v1/champion-summary.json'); // 9bec0e9708f39d1f
hash_name('rcp-be-lol-game-data', 'es_es', '/lol-game-data/assets/v1/champion-summary.json'); // 660c1969b03ecdb8
```
Those are all valid files, downloaded from the projects 'league_client', 'league_client_pt_br' and 'league_client_es_es'.

Loading the 'champion-summary.json' (of any given language/project), it is possible to find all the champion_ids, which can be used on the `hash_name` method again to find out their correct hash on the given language/project.

**Comment by Pupix** [comment]
@honux can you open a new issue for this?

I am also looking at the way the [unicode guys](http://unicode.org/) are organizing their [CLDR repo](https://github.com/unicode-cldr/cldr-numbers-modern) to handle multiple languages. Theoretically we could have the same `hashes/<location>/<plugin_name>.json` file structure.

This way we could update and handle plugins separately, without having to update the huge hashes file when only 1 plugins changes.
